FROM owncloud/ubuntu:18.04@sha256:253a8ef18be1e161ab59d919a430fba0f91ed36c951d9dc3fb2e61e9395eccfc

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI Oracle XE"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/oracle-xe"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/oracle-xe"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/oracle-xe"

ENV ORACLE_HOME /u01/app/oracle/product/11.2.0/xe
ENV PATH $ORACLE_HOME/bin:$PATH
ENV ORACLE_SID XE
ENV DEBIAN_FRONTEND noninteractive

COPY rootfs /

# Install sshd
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y openssh-server && \
    mkdir /var/run/sshd && \
    echo 'root:admin' | chpasswd && \
    sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config && \
    echo "export VISIBLE=now" >> /etc/profile

# Prepare to install Oracle
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y libaio1 net-tools bc && \
    ln -s /usr/bin/awk /bin/awk && \
    mkdir -p /var/lock/subsys || true

# Install Oracle
RUN cat /oracle/oracle-xe_11.2.0-1.0_amd64.deba* > /oracle/oracle-xe_11.2.0-1.0_amd64.deb && \
    dpkg --install /oracle/oracle-xe_11.2.0-1.0_amd64.deb && \
    mv /oracle/init.ora /u01/app/oracle/product/11.2.0/xe/config/scripts && \
    mv /oracle/initXETemp.ora /u01/app/oracle/product/11.2.0/xe/config/scripts && \
    printf 8080\\n1521\\noracle\\noracle\\ny\\n | /etc/init.d/oracle-xe configure && \
    echo 'export ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe' >> /etc/bash.bashrc && \
    echo 'export PATH=$ORACLE_HOME/bin:$PATH' >> /etc/bash.bashrc && \
    echo 'export ORACLE_SID=XE' >> /etc/bash.bashrc && \
    rm -rf /oracle/oracle-xe_11.2.0-1.0_amd64.deb* && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 22
EXPOSE 1521
EXPOSE 8080

CMD sed -i -E "s/HOST = [^)]+/HOST = $HOSTNAME/g" /u01/app/oracle/product/11.2.0/xe/network/admin/listener.ora; \
	  service oracle-xe start; \
	  sqlplus -s -l system/oracle @owncloud; \
	  /usr/sbin/sshd -D
